[profile.default]
src = 'contracts'
out = 'out'
#viaIR = true
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
offline = true

[profile.lite.optimizer_details.yulDetails]
optimizerSteps = ''